# Generated by Django 4.2 on 2024-08-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='link',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='ссылка на оплату'),
        ),
        migrations.AddField(
            model_name='payments',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='айди сессии'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='price',
            field=models.PositiveIntegerField(verbose_name='сумма оплаты'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
