# Generated by Django 4.2 on 2024-08-19 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0010_alter_course_price'),
        ('users', '0005_payments_link_payments_session_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='link',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='session_id',
        ),
        migrations.AlterField(
            model_name='payments',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='сумма оплаты'),
        ),
        migrations.CreateModel(
            name='CoursePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма оплаты')),
                ('session_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID сессии')),
                ('link', models.URLField(blank=True, max_length=400, null=True, verbose_name='Ссылка на оплату')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.course', verbose_name='Курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Покупка курса',
                'verbose_name_plural': 'Покупки курсов',
            },
        ),
    ]
