# Generated by Django 4.2 on 2024-07-09 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название урока')),
                ('description', models.TextField(verbose_name='Описание урока')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='lessons.photo', verbose_name='Превью урока')),
                ('link', models.URLField(verbose_name='ссылка на урок')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название курса')),
                ('description', models.TextField(verbose_name='Описание курса')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='course/photo', verbose_name='Превью курса')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.lesson', verbose_name='Уроки курса')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
    ]
