# Generated by Django 4.2 on 2024-08-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=100, verbose_name='цена'),
        ),
    ]
